### ISSUE TITLE
Dependency security vulnerability will be a good addition. 

### ISSUE THREAD

**Issue by chowmean** [olacabs/jackhammer#10]
Generally devs use dependencies with out checking for vulnerabilities in those dependencies. It could be a great addition. 
**Listing few of the tools below.**
1. Safety db.
2. nsp for Node.
3. security checker from sensiolabs for php.
4. Bundler audit you have already integrated.

**Comment by shadsidd** [comment]
@chowmean NSP and Bundler audit is already there. Rest you could go ahead and add any tool in few minutes https://jch.olacabs.com/userguide/adding_new_tool/
