### ISSUE TITLE
branch jch-v2 login not working for signup or default credentials

### ISSUE THREAD

**Issue by kempy007** [olacabs/jackhammer#117]
None of your builds work, 
V1 has issue with DB and mocha package missing. 
V2 comes up but cannot login or signup (maybe upstream package changes).

Is there a working image on docker hub??

**Comment by kmadhusudhan** [comment]
Can please make all below services running by running  **docker ps**  
jchclient
jch-server 
jch-db
jch-marathon
jch-mesos-slave
jch-mesos-master
jch-zookeeper

**Comment by kempy007** [comment]
They were running on the jch-v2 branch build. The landing page/product facts was displayed at port 5005 but authentication seems broken.

**Comment by kmadhusudhan** [comment]
can please check default db data by logging into MySQL container. you can get default db data from https://github.com/olacabs/jackhammer/blob/jch-v2/dump.sql . And there is no clue for me to solve your issue, can please  browser console error and docker logs for jackhammer server

**Comment by kempy007** [comment]
Sorry I've given up on this and have moved on, since the online demo had no import feature I could see. I don't have time to spend days/weeks trying to get something running to find I can't use it how I'd like. But I'd suggest making an all in one demo container that's as easy as a docker pull to get up and running.
