### ISSUE TITLE
Integration with Checkmarx and HP WI

### ISSUE THREAD

**Issue by MarcOak** [olacabs/jackhammer#17]
Regarding the integration with Checkmarx, does it need to be installed on the same server as jackhammer? Can I somehow leverage exiting Checkmarx install through API calls to kick off the scans?  Same for HP WebInspect?
Thanks
Marcelo

**Comment by shadsidd** [comment]
@MarcOak Nope, Checkmarx server needs to be accessible from jackhammer server and you can just put in the server details and creds in Admin Settings to kick it off on all the scan.
With HP Webinspect we do not have API integration yet, you have to upload the file via upload scans
