### ISSUE TITLE
Add Tools : AltDNS not running 

### ISSUE THREAD

**Issue by omarkurt** [olacabs/jackhammer#28]
lib/pipeline/task below : 

https://gist.github.com/omarkurt/c538d5fd4bf277fd97a71d73c0ae2bff 

docker-compose stop
docker-compose rm
sudo sh docker-build.sh SignleUser

How debug adding tool?

**Comment by 1ab1** [comment]
@omarkurt 
There is a typo in 3rd step.
~~sudo sh docker-build.sh SignleUser~~
`sudo sh docker-build.sh SingleUser`
1. First, make sure that all the  dependencies are resolved and you can run `AltDns` manually inside the container.
2.  While running the scan,  check sidekiq logs `tail -f log/sidekiq.log ` for any tool related error.

Let me know if you still face any issues.
