### ISSUE TITLE
Couldn't find option for authenticated web app scan?

### ISSUE THREAD

**Issue by ashu2188** [olacabs/jackhammer#3]
Hi,

Is there any option in jackhammer that allows authenticated web scan? I looked around after setting it up but couldn't find anything.

Thanks,
Ashutosh

**Comment by NitescuLucian** [comment]
Same! It will take me some time to find how I can help the development process. 👍

**Comment by shadsidd** [comment]
@ashu2188 @NitescuLucian : It's there internally, we would commit the changes in 1-3 days.

**Comment by NitescuLucian** [comment]
@shadsidd perfect!

**Comment by NitescuLucian** [comment]
@shadsidd any update?

**Comment by shadsidd** [comment]
@NitescuLucian Fixed in latest commit, please check.
