### ISSUE TITLE
jackhammer build failed

### ISSUE THREAD

**Issue by sampathmende** [olacabs/jackhammer#62]
I typed below command to build the jackhammer 
docker-compose up -d
then its not building the application getting following error
OS : Windows 10

Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
The git source `git://github.com/rweng/jquery-datatables-rails.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/sumoheavy/jira-ruby.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching gem metadata from https://rubygems.org/........
Fetching git://github.com/sumoheavy/jira-ruby.git
fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=Connection refused
github.com[1: 192.30.255.113]: errno=Connection refused

Retrying `git clone 'git://github.com/sumoheavy/jira-ruby.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jira-ruby-523bdb9909e000ebe1af25417e77e49b15b44a72" --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/sumoheavy/jira-ruby.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jira-ruby-523bdb9909e000ebe1af25417e77e49b15b44a72" --bare --no-hardlinks --quiet` in directory /tmp has failed.fatal: unable to connect to github.com:
github.com[0: 192.30.255.113]: errno=Connection refused
github.com[1: 192.30.255.112]: errno=Connection refused

Retrying `git clone 'git://github.com/sumoheavy/jira-ruby.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jira-ruby-523bdb9909e000ebe1af25417e77e49b15b44a72" --bare --no-hardlinks --quiet` due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/sumoheavy/jira-ruby.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jira-ruby-523bdb9909e000ebe1af25417e77e49b15b44a72" --bare --no-hardlinks --quiet` in directory /tmp has failed.fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Connection refused
github.com[1: 192.30.253.112]: errno=Connection refused

Git error: command `git clone 'git://github.com/sumoheavy/jira-ruby.git'
"/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jira-ruby-523bdb9909e000ebe1af25417e77e49b15b44a72"
--bare --no-hardlinks --quiet` in directory /tmp has failed.
Service 'web' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 11

**Comment by sampathmende** [comment]
I have been trying to fix the issue with replacing http with https  in gitconfig file
[url "https://github.com"]
	insteadOf = git://github.com

But not fixed

**Comment by kmadhusudhan** [comment]
can please take the fresh clone and  run the jackahmmer

**Comment by sampathmende** [comment]
I have taken fresh clone of jackhammer and run the following commands
git clone https://github.com/olacabs/jackhammer    - cloning new 
 sh ./docker-build.sh  - for building

**Got below error** 
Step 39/48 : RUN bash bundle.sh
 ---> Running in b975c11cee26
bundle.sh: line 13: syntax error: unexpected end of file
Service 'web' failed to build: The command '/bin/sh -c bash bundle.sh' returned a non-zero code: 2

and tried with single user mode also with below command
sh ./docker-build.sh SingleUser
Getting same error

**Step 39/48 : RUN bash bundle.sh
 ---> Running in b975c11cee26
bundle.sh: line 13: syntax error: unexpected end of file
Service 'web' failed to build: The command '/bin/sh -c bash bundle.sh' returned a non-zero code: 2**

**Comment by Nishtha04** [comment]
Remove all the docker images, volumes, network and containers. Also clear the cache and then do a fresh install of jackhammer. It should work.

**Comment by sampathmende** [comment]
I have removed all the docker images ,volumes, network and containers and clear the cache. Then removed the existing jackhammer and cloned new one then gave the build and getting below error.

**Used below commands to clear the images,volumes,containers,network and cache.
docker image prune -a
ocker container prune
docker volume prune
docker network prune
docker system prune
docker system prune --volumes
docker system prune -a
docker stop $(docker ps -a -q)
 docker rm $(docker ps -a -q)


bundle.sh: line 13: syntax error: unexpected end of file
Service 'web' failed to build: The command '/bin/sh -c bash bundle.sh' returned a non-zero code: 2
this it took 1 hr to return this error.**

Your help is appreceited

**Comment by Nishtha04** [comment]
Open web/Dockerfile and see if there is comment on line 69 

#RUN bundle install
RUN bash bundle.sh

If yes, try removing the '#' and try again.

**Comment by Nishtha04** [comment]
I just noticed you are trying to run it on windows 10. Docker is running a linux VM. Try running below commands too. Hope that will resolve your problem.

dos2unix /web/bundle.sh
dos2unix docker-build.sh

**Comment by sampathmende** [comment]
when i have to run these commands immediately after build command??
in below order or any other order please let me know
 **1. sh ./docker-build.sh
 2. dos2unix /web/bundle.sh
 3. dos2unix docker-build.sh

PS : I am running commands on GitBash editor**

Thanks,
Sampath

**Comment by sampathmende** [comment]
I have followed which you mentioned but again iam getting below error.


Step 39/49 : RUN bundle install
 ---> Running in 513af5f826be
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
The git source `git://github.com/rweng/jquery-datatables-rails.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/sumoheavy/jira-ruby.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching gem metadata from https://rubygems.org/........
Fetching git://github.com/sumoheavy/jira-ruby.git
fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=Connection refused
github.com[1: 192.30.255.113]: errno=Connection refused


Retrying `git clone 'git://github.com/sumoheavy/jira-ruby.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jira-ruby-523bdb9909e000ebe1af25417e77e49b15b44a72" --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/sumoheavy/jira-ruby.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jira-ruby-523bdb9909e000ebe1af25417e77e49b15b44a72" --bare --no-hardlinks --quiet` in directory /tmp has failed.fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Connection refused
github.com[1: 192.30.253.113]: errno=Connection refused


Retrying `git clone 'git://github.com/sumoheavy/jira-ruby.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jira-ruby-523bdb9909e000ebe1af25417e77e49b15b44a72" --bare --no-hardlinks --quiet` due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/sumoheavy/jira-ruby.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jira-ruby-523bdb9909e000ebe1af25417e77e49b15b44a72" --bare --no-hardlinks --quiet` in directory /tmp has failed.fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Connection refused
github.com[1: 192.30.253.113]: errno=Connection refused


Retrying `git clone 'git://github.com/sumoheavy/jira-ruby.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jira-ruby-523bdb9909e000ebe1af25417e77e49b15b44a72" --bare --no-hardlinks --quiet` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/sumoheavy/jira-ruby.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jira-ruby-523bdb9909e000ebe1af25417e77e49b15b44a72" --bare --no-hardlinks --quiet` in directory /tmp has failed.fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Connection refused
github.com[1: 192.30.253.112]: errno=Connection refused


Git error: command `git clone 'git://github.com/sumoheavy/jira-ruby.git'
"/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jira-ruby-523bdb9909e000ebe1af25417e77e49b15b44a72"
--bare --no-hardlinks --quiet` in directory /tmp has failed.
Service 'web' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 11

Thanks in advance
Sampath

**Comment by Nishtha04** [comment]
Ah, at least you have got some other error now :)

Are you sure you have the latest clone of project?

Check in your Dockerfile under web if you are running bundle command as root. If yes, remove it.

For https refer to this URL https://github.com/olacabs/jackhammer/pull/13/files

For Git error, seems like your git port is restricted. Try making changes in your Gemfile.lock and replace git://github.com with global URL https://github.com

**Comment by sampathmende** [comment]
Unfortunately u r comments are not helpful. Can you please mention clearly as i am new to this. 
**Pls check inline comments**


![docker](https://user-images.githubusercontent.com/22193461/33752243-af52fb54-dc06-11e7-9a57-9bdb5f2b007b.JPG)
 Are you sure you have the latest clone of project?  -I have cloned new project when build fails then i am removing all the images,containers,volums,network,cache and doing build again**

Check in your Dockerfile under web if you are running bundle command as root. If yes, remove it.
- I checked the docker file but how i can confirm that running bundle command as root ?? if yes how can i stop that ? pls explain

For https refer to this URL https://github.com/olacabs/jackhammer/pull/13/files  - why is this url ?? I opened it but not understood

For Git error, seems like your git port is restricted. Try making changes in your Gemfile.lock and replace git://github.com with global URL https://github.com
- whats the location of Gemfile.lock and how to replace it?? By the way I tried  in .git.config file  initially but didnt work?
Docker file screenshot attached .  Thanks for replying :) 👍 
Pls help  Been trying for morethan two weeks now

**Comment by Nishtha04** [comment]
Seems like you haven't explored the project by yourself :) you have to explore project by yourself a bit buddy.

Anyway I have clearly mentioned to check Dockerfile under web i.e. web/Dockerfile, and you can search for bundle.sh and see if you have added sudo in that.

This URL https://github.com/olacabs/jackhammer/pull/13/files clearly says in which file you have to make changes and what are those changes. I don't understand what you didn't get.

Again for Git, you can find Gemfile.lock file under web/app Changes are mentioned in my above comment.

**Comment by sampathmende** [comment]
Thanks for clarifying and i have changed the git port to global url  in gemfile.lock file and updated application.rb file with config.fort_ssl = true also.  and there is no sudo before RUN bundle.sh command also.
But still i am getting below issue

Step 39/49 : RUN bundle install
 ---> Running in 8355711feaef
**Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.**
**The git source `git://github.com/rweng/jquery-datatables-rails.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/sumoheavy/jira-ruby.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/rweng/jquery-datatables-rails.git**

Retrying `git clone 'git://github.com/rweng/jquery-datatables-rails.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jquery-datatables-rails-b8d699e208e47fe51869a7aebe3d593ff0672f4a" --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/rweng/jquery-datatables-rails.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jquery-datatables-rails-b8d699e208e47fe51869a7aebe3d593ff0672f4a" --bare --no-hardlinks --quiet` in directory /tmp has failed.fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Connection refused
github.com[1: 192.30.253.112]: errno=Connection refused

fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=Connection refused
github.com[1: 192.30.255.113]: errno=Connection refused


Retrying `git clone 'git://github.com/rweng/jquery-datatables-rails.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jquery-datatables-rails-b8d699e208e47fe51869a7aebe3d593ff0672f4a" --bare --no-hardlinks --quiet` due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/rweng/jquery-datatables-rails.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jquery-datatables-rails-b8d699e208e47fe51869a7aebe3d593ff0672f4a" --bare --no-hardlinks --quiet` in directory /tmp has failed.fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=Connection refused
github.com[1: 192.30.255.113]: errno=Connection refused


Retrying `git clone 'git://github.com/rweng/jquery-datatables-rails.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jquery-datatables-rails-b8d699e208e47fe51869a7aebe3d593ff0672f4a" --bare --no-hardlinks --quiet` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/rweng/jquery-datatables-rails.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jquery-datatables-rails-b8d699e208e47fe51869a7aebe3d593ff0672f4a" --bare --no-hardlinks --quiet` in directory /tmp has failed.fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=Connection refused
github.com[1: 192.30.255.113]: errno=Connection refused


Git error: command `git clone
'git://github.com/rweng/jquery-datatables-rails.git'
"/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jquery-datatables-rails-b8d699e208e47fe51869a7aebe3d593ff0672f4a"
--bare --no-hardlinks --quiet` in directory /tmp has failed.

**Comment by Nishtha04** [comment]
Where all you made changes in Gemfile.lock ?

You can see by yourself where the error is ;) 

Before it was in **git clone 'git://github.com/sumoheavy/jira-ruby.git** where you have changed the URL to global URL and now it's in git clone '**git://github.com/rweng/jquery-datatables-rails.git** 

You need to make changes throughout your file to make it work.

**Comment by sampathmende** [comment]
please find the gemfile.lock file where in 2 places i have changed it. I searched through the file but found it 2 places and changed it. Gave the build after changing in 2 places but got the above error.
What i feel like Its not taking path from this file or what ?? or taking its from any cache??/
![gemfile](https://user-images.githubusercontent.com/22193461/33759060-eb6ac214-dc26-11e7-8912-7af4e42e9fa9.JPG)

**Comment by sampathmende** [comment]
Now I installed oracle vm and docker toolbox and run the docker build for jackhammer
 Its giving error while installing jdk 8 
dpkg error processing  oracle-java8-installer  (--configure)
sub process installed post installation script returned error exit status 1
Error were encountered while processing oracle-java8-installer
sub process /usr/bin/dpkg  returned an error code 1
Error service web failed to build 
the command  bin/sh -c echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \rm -rf /var/cache/oracle-jdk8-installer returned non zero code 100

**Comment by sampathmende** [comment]
solved so closing
