### ISSUE TITLE
Jackhammer build failed with below error

### ISSUE THREAD

**Issue by sampathmende** [olacabs/jackhammer#69]
I have taken fresh clone of jackhammer.
I downloaded docker for windows and its up and running after spending lot of time on it. enabled hyper v also.
downloaded powershell to run the commands
executed below commands in powershell
 git clone https://github.com/olacabs/jackhammer
 sh ./docker-build.sh

made changes in your Gemfile.lock and replaced git://github.com with global URL https://github.com
removed comment before #RUN bundle install.
Got below error
Step 1/49 : FROM ubuntu:14.04
14.04: Pulling from library/ubuntu
Service 'web' failed to build: no matching manifest for windows/amd64 in the manifest list entries
Creating network "jackhammer_default" with the default driver
HNS failed with error : The system cannot find the file specified.
Creating network "jackhammer_default" with the default driver
HNS failed with error : The system cannot find the file specified.
Creating network "jackhammer_default" with the default driver
HNS failed with error : The system cannot find the file specified.
Creating network "jackhammer_default" with the default driver
HNS failed with error : The system cannot find the file specified.
Creating network "jackhammer_default" with the default driver
HNS failed with error : The system cannot find the file specified.

admin@sampath MINGW64 /c/jackhammer (master)
$ sh ./docker-build.sh SingleUser
mysqldb uses an image, skipping
redis uses an image, skipping
Building web
Step 1/49 : FROM ubuntu:14.04
14.04: Pulling from library/ubuntu
Service 'web' failed to build: no matching manifest for windows/amd64 in the manifest list entries
Creating network "jackhammer_default" with the default driver
HNS failed with error : The system cannot find the file specified.
Creating network "jackhammer_default" with the default driver
HNS failed with error : The system cannot find the file specified.
Creating network "jackhammer_default" with the default driver
HNS failed with error : The system cannot find the file specified.
Creating network "jackhammer_default" with the default driver
HNS failed with error : The system cannot find the file specified.
Creating network "jackhammer_default" with the default driver
HNS failed with error : The system cannot find the file specified.

Pls help

**Comment by kmadhusudhan** [comment]
please check your docker version, it should be above  17.03.1.  please refer this to installation https://jch.olacabs.com/userguide/installation/

**Comment by sampathmende** [comment]
I followed the above link to install jackhammer. and documentation is not clear.
I think prerequisites are Docker,powershell, installation ,But nothing is mentioned in the above document.
 I have installed everything and but getting above issue

host distribution and version (Windows version, build number, etc)
Windows 10 Pro
version : 1709
OS build :16299.125
Docker version ::
Version 17.09.1-ce-win42 (14687)
Channel: stable
3176a6a

**Comment by sampathmende** [comment]
Now I installed oracle vm and docker toolbox and run the docker build for jackhammer
 Its giving error while installing jdk 8 
dpkg error processing  oracle-java8-installer  (--configure)
sub process installed post installation script returned error exit status 1
Error were encountered while processing oracle-java8-installer
sub process /usr/bin/dpkg  returned an error code 1
Error service web failed to build 
the command  bin/sh -c echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \rm -rf /var/cache/oracle-jdk8-installer returned non zero code 100

**Comment by kmadhusudhan** [comment]
docker not able install java ,Some how you need to install java inside docker

**Comment by sampathmende** [comment]
I modified Gemfile.lock with global urls like instead of git:// used https:// but still getting below error.
almost 1 month back raised defects it seems no one is paying attention it. sorry.


The git source `git://github.com/rweng/jquery-datatables-rails.git` uses the `git` protocol, which transmits data without encryption. Disable this war
ning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/sumoheavy/jira-ruby.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with
`bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/rweng/jquery-datatables-rails.git

Retrying `git clone 'git://github.com/rweng/jquery-datatables-rails.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jquery-dat
atables-rails-b8d699e208e47fe51869a7aebe3d593ff0672f4a" --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git e
rror: command `git clone 'git://github.com/rweng/jquery-datatables-rails.git' "/root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/cache/bundler/git/jquer
y-datatables-rails-b8d699e208e47fe51869a7aebe3d593ff0672f4a" --bare --no-hardlinks --quiet` in directory /tmp has failed.fatal: unable to connect to g
ithub.com:
github.com[0: 192.30.253.113]: errno=Connection timed out
github.com[1: 192.30.253.112]: errno=Connection timed out
